spring:
    application:
        name: rakuten-dnd-character-app
    data:
        mongodb:
            uri: mongodb+srv://rajat8527:HDFCILU123$@headout-statz.mongodb.net/dnd?retryWrites=true&w=majority